### ISSUE TITLE
Clarify mapping of SQL result sets to entity lists

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#124]
In the JPA 2.1 spec, I cannot find any details about the mapping of SQL result rows to the list of results returned from an entity query.

The result of the following query seems to depend on the used collection types and on the JPA implementation which is not desirable:

Example: Suppose there is a Person with two addresses and two phone numbers.

```
select distinct p from Person p 
left join fetch p.addresses 
left join fetch p.phoneNumbers 
where p.id = 1
```

The underlying SQL query will return 4 rows, and the result list is a single Person entity, where the collections may be incorrect, with 4 addresses or 4 phone numbers or even both.

The number of duplicates is influenced by the collection types:
<tt>List</tt> without <tt>@OrderColumn</tt>, <tt>List</tt> with <tt>@OrderColumn</tt> or <tt>Set</tt>.

The specification should define warnings or exceptions for cases that would lead to incorrect duplicates.
#### Affected Versions
[2.1.1]

**Comment by gavinking** [comment]
I agree with @neilstockton. These are not details that the spec should be getting involved in.

> The specification should define warnings or exceptions for cases that would lead to incorrect duplicates.

Nope, fetching collections in parallel is a very tricky thing that should be left up to the implementations. The JPA spec should remain silent on these topics.

This issue is eight years old with no votes. Closing.
