### ISSUE TITLE
Auto-Quote database identifiers to avoid use of SQL keywords

### ISSUE THREAD

**Issue by gergelymolnarpro** [jakartaee/persistence#237]
Standardise hibernate.globally_quoted_identifiers, because when we create Java classes, we should not care about reserved SQL keywords.

Example: we can't create Release named class (or @Entity(name="Release") ) if we use MySQL database with JPA api.

**Comment by andyjefferson** [comment]
+1 for auto-quoting database identifiers when necessary to avoid use of SQL keywords (*not* adding some Hibernate property), but then other persistence providers (e.g DataNucleus) have done that for years (before the JPA spec). 

Suggest that you change the title of this issue to something like "Auto-Quote database identifiers to avoid use of SQL keywords" ... the current title is way too generic and could mean many things to many people

**Comment by gavinking** [comment]
The Hibernate team doesn't recommend the use of `hibernate.globally_quoted_identifiers` so I agree that JPA should not add anything like that.

**Comment by beikov** [comment]
I guess what you are after is `hibernate.auto_quote_keyword`, but IMO this should be enabled by default in Hibernate. Not sure if the JPA spec should specify this behavior, but it's for sure a problem of Hibernate because it didn't enable this setting by default.

**Comment by gavinking** [comment]
It's a hard call, and I'm not sure what the spec should day. 

It's pretty hard for the spec to demand that the implementations auto-quote every single keyword on every single database they support. (How would you even test for compliance with that demand?)

On the other hand, I agree that it's a desirable default behavior.

I wondered if there was some sort of reasonable compromise: that the implementations should quote all ANSI SQL keywords, or something like that, but that doesn't seem to work either, since ANSI defines many irrelevant keywords.

I'm not sure. Tricky one.

**Comment by gavinking** [comment]
Alright, so the thing I forgot about is case-sensitivity. Quoting identifiers makes them case-sensitive, which can cause problems since, when the column name is inferred from a Java field name, JPA just doesn't know the case on the database.

Now, it might seem like, well, we should quote it *anyway*, since using a keyword as a table or column name is sure to fail *anyway*, so we can just at least do a best-effort.

But that's not actually true. Lots of databases will accept a keyword column or table name depending on how it occurs syntactically. E.g. you can easily have a column called `key` on (some? most?) databases.

So, for example, if I have a table with a column named `KEY` in uppercase, and a Java field `String key`, then that works today. But if we turn on auto-quoting, that working code actually will break!

So it turns out that this issue is a whole lot more subtle than it looks.

On balance it might be best if the spec stays silent on this issue, and recommends, where necessary, the use of, e.g. `@Column(name="\"KEY\"")`.

**Comment by lukasj** [comment]
The only thing I can imagine we could do here at the spec level would be to define ~2 properties -  one for auto-quoting and the other for auto-uppercase naming - to leverage functionality providers already have support for, with semantics  similar to query hints (either support or ignore). In general, I can agree with this being useful, OTOH the decision to turn this on should be always left up to the user, since consequences of having this on are really dependent not only on particular DB but also on its particular version (ie RANK in mysql 5 vs 8)

**Comment by gavinking** [comment]
@lukasj Yeah, I think what you just said is about right.

OTOH, I'm skeptical that adding such optional settings to the spec is of much value, especially if we can't reasonably guarantee that the behavior is going to be very portable. (And I don't think we can really.)

**Comment by lukasj** [comment]
@gavinking so just close this leaving it up to vendors to deal with this sort of issues? I'm fine with that, even from eclipselink's point of view.

**Comment by gavinking** [comment]
Yes, on balance I think it's probably best.

**Comment by gavinking** [comment]
@lukasj I think we can just close this one.

**Comment by dmatej** [comment]
I would like to reopen this, because I spent with this yesterday evening. Many databases now support case sensitive scheme, including Informix and Postgress and Jakarta Persistence then doesn't work well with that - I had to add `orm.xml` with this content to make it work, which is a lot of additional boilerplate.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<entity-mappings
    xmlns="https://jakarta.ee/xml/ns/persistence/orm"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence/orm https://jakarta.ee/xml/ns/persistence/orm/orm_3_2.xsd"
    version="3.2">
    <persistence-unit-metadata>
        <persistence-unit-defaults>
            <delimited-identifiers/>
        </persistence-unit-defaults>
    </persistence-unit-metadata>
</entity-mappings>

```

AI originally recommended to "hijhack" the `Table` and `Column` annotation this way and I remembered I already used that some 15 years ago with Informix or MSSQL db, not sure now: 
```java
@Table(name = "`MyTable`")
```

When I complained that it should be easier, Claude recommended something that did not work at least with EclipseLink, however I would take it as how I would expect it would work with `persistence.xml`.
```xml
<property name="jakarta.persistence.quote-all-identifiers" value="true"/>
```

I see Hibernate already supports it using own property and I did not notice anyone would make it deprecated. Instead, Hibernate elaborated it to multiple strategies (not sure if that is useful, might be if the db scheme script is a bit messy and sometimes uses quotes, sometimes not, then it can get quite complicated; however it should be always safe when we would use quotes and exact names, which is why I prefer quoting in my projects).
* https://docs.hibernate.org/orm/current/javadocs/org/hibernate/cfg/MappingSettings.html#GLOBALLY_QUOTED_IDENTIFIERS
* https://www.baeldung.com/hibernate-naming-strategy

If we would make it a standard in the simplest way, we would have to decide what has the higher priority, if the property or the `orm.xml` file. As it already works with the `orm.xml` file, I believe we would not need to define what should be affected. That is probably already done.

Actually this is not just about keywords, see an example:
```sql
CREATE TABLE IF NOT EXISTS "GlassFishUser" (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255)
);
```
```java
@Entity
@Table(name = "GlassFishUser")
public class User implements Serializable {
    private static final long serialVersionUID = 3512031996296372413L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column
    private String name;
...
```
And these are logs from Postgress database when you call `em.persist(x)`:
```log
2026-03-11 11:20:21.404 UTC [81] STATEMENT:  INSERT INTO GlassFishUser (NAME) VALUES ($1)
2026-03-11 11:20:21.404 UTC [80] ERROR:  relation "glassfishuser" does not exist at character 13
```

**Comment by gavinking** [comment]
@dmatej It's not clear what feature you're requesting. Global quoting or keyword auto-quoting?

**Comment by dmatej** [comment]
> [@dmatej](https://github.com/dmatej) It's not clear what feature you're requesting. Global quoting or keyword auto-quoting?

As it is written in the title, adding a property which would enable "_auto-quoting database identifiers_". I would just remove the rest of the title, because conflicts with keywords are not the only reason - even a DDL script can make table/column/... names case sensitive. Then any uppercase/lowercase strategy doesn't work, you simply need to quote these names (or better all names as usually whole DDL script keeps the same pattern).

Aha, I see the misunderstanding ... by auto-quoting I mean quoting all database identifiers.

Right now it already works with the `orm.xml` file as I wrote in the example, but it is a lot of boilerplate - I think it would be easier if it would be configurable using properties.
https://jakarta.ee/specifications/persistence/3.2/jakarta-persistence-spec-3.2#delimited-identifiers

**Comment by tooldevops** [comment]
+1

> > [@dmatej](https://github.com/dmatej) It's not clear what feature you're requesting. Global quoting or keyword auto-quoting?
> 
> As it is written in the title, adding a property which would enable "_auto-quoting database identifiers_". I would just remove the rest of the title, because conflicts with keywords are not the only reason - even a DDL script can make table/column/... names case sensitive. Then any uppercase/lowercase strategy doesn't work, you simply need to quote these names (or better all names as usually whole DDL script keeps the same pattern).

**Comment by gavinking** [comment]
> by auto-quoting I mean quoting all database identifiers

And what is the use case you envision for this?

[Remember, global quoting doesn't work at all when mapping an existing database schema, as I already explained, so you must be thinking of some other circumstance.]

**Comment by dmatej** [comment]
> [Remember, global quoting doesn't work at all when mapping an existing database schema, as I already explained, so you must be thinking of some other circumstance.]

Disagree, my experience is exactly opposite - it works perfectly (with EclipseLink), while without it there's no way I could work with such existing scheme in PostgreSQL (I even tried older PG versions with the same result).
I am quite sure we could find problematic JPQL/SQL queries, however ... I have to say again, via orm.xml it is already requested and supported since JPA 2.0. This would just simplify the configuration.

**Comment by gavinking** [comment]
OK, then, so I must be missing something.

So let's say I have the following legacy schema:

```sql
CREATE TABLE BOOK (ISBN VARCHAR(13) PRIMARY KEY, TITLE VARCHAR(500), TEXT CLOB);
```

And this Java class:

```java
@Entity
class Book {
    @Id String isbn;
    String title;
    String text;
}
```

and you turn on global identifier quoting.

You're telling me that this code works in EclipseLink?

How?? What SQL does EclipseLink generate?

**Comment by tooldevops** [comment]
The starting point of this topic is that you simply cannot use classes as-is if they use reserved keywords from the database language without some kind of workaround. Also, the idea is: why should someone designing Java-level code have to cross-reference the language of another layer just to avoid errors?

**Comment by gavinking** [comment]
>  why should someone designing Java-level code have to cross-reference the language of another layer just to avoid errors?

That question is incredibly easy to answer: because in more than 90% of cases you are mapping to an existing legacy database schema. It's very often possible to line up names (e.g. `BOOK` vs `Book` in my example). It's almost never possible to line up capitalization conventions. 

I have never seen a legacy database which conforms to the Java conventions of:

1.  case sensitivity,
2. `PascalCase` for tables,  and
3.  `camelCase` for columns.

Perhaps some such databases exist; they are not common.

**Comment by gavinking** [comment]
And @tooldevops please use your real name here. I will not interact further with anonymous accounts. Sorry.

**Comment by gergelymolnarpro** [comment]
> And [@tooldevops](https://github.com/tooldevops) please use your real name here. I will not interact further with anonymous accounts. Sorry.

Alright, I don't use this profile anymore, but for what it's worth: I’m also 'tooldevops' here. Where I work, we have new projects starting all the time. Why is it so common to assume we only ever work with legacy databases? Statistics show that new backends are created every single day. Whether a project is new or legacy should not influence whether this functionality is useful or not.

I don't want to get into a debate, but that’s exactly why "starter" generator tools for web apps are so popular and 'vibe' is a huge trend right now.

**Comment by gavinking** [comment]
> Why is it so common to assume we only ever work with legacy databases?  

All I said is that pre-existing is the common case. Of course it's not the only case.

But even for a new project, most people don't want to use quoted identifiers everywhere.

Why not? Well, _for example_, if I export this schema:

```java
CREATE TABLE "Book" ("isbn" VARCHAR(13) PRIMARY KEY, "title" VARCHAR(500));
```

Then look what happens on Postgres  (at least by default):

```
hibernate_orm_test=# select * from Book;
ERROR:  relation "book" does not exist
LINE 1: select * from Book;
                      ^
hibernate_orm_test=# select * from book;
ERROR:  relation "book" does not exist
LINE 1: select * from book;
                      ^
hibernate_orm_test=# select * from BOOK;
ERROR:  relation "book" does not exist
LINE 1: select * from BOOK;
                      ^
```

So I would just stay away from quoted mixed case identifiers.

**Comment by gavinking** [comment]
> I have to say again, via `orm.xml` it is already requested and supported since JPA 2.0. This would just simplify the configuration.

So the thing here is that `orm.xml` is one of the two places that JPA lets you specify *mapping* information. We do not currently have any standard property that affects mappings. I'm all for specifying variable *configuration* via properties. I'm not at all keen on specifying static mapping information via properties.

**Comment by OndroMih** [comment]
@gavinking 

> Then look what happens on Postgres (at least by default):

Isn't this exactly what @dmatej describes as a problem? If Postgre's table is named "Book", then EclipseLink, and probably also Hibernate, create an unquoted query `select * from Book`, which is translated to lowercase by the dabase, ie. `select * from book`, and then the DB can't find the `book` table. 

If the SQL produced by the JPA provider contained quotes in the first place, ie. `select * from "Book"`, then the DB would map it to `"Book"` and would be able to find the table.

**Comment by gavinking** [comment]
@OndroMih No, you have it exactly backwards.

- If the Postgres table was created, as is almost always the case, with an unquoted identifier, then it doesn't matter whether the JPA provider sends the table name as `Book`, `book`, or `BOOK`, it just works. Because SQL is not a case sensitive language.
- In the much, much less common case that someone creates a table with an explicitly quoted name then suddenly it _does_ matter, and the casing of the table name in the mappings has to _exactly match_ the casing of the name in the database, which means, essentially, that the user will likely have to scatter explicit `@Column` and `@Table` annotations all over their entities. And in their native SQL queries they have to add explicit quotes, writing this sort of ugliness: `"select * from \"Book\""`.

This is what the Hibernate documentation says.

<img width="1012" height="648" alt="Image" src="https://github.com/user-attachments/assets/945ab33a-b9e9-41a2-bff0-bd8d086939da" />

So this issue is requesting standardization of a feature of Hibernate that the Hibernate team explicitly discourages.

**Comment by gavinking** [comment]
> > I have to say again, via `orm.xml` it is already requested and supported since JPA 2.0. This would just simplify the configuration.
> 
> So the thing here is that `orm.xml` is one of the two places that JPA lets you specify _mapping_ information. We do not currently have any standard property that affects mappings. I'm all for specifying variable _configuration_ via properties. I'm not at all keen on specifying static mapping information via properties.

By the way, a couple of months ago, I proposed introducing a `@PersistenceModule` annotation for this sort of "persistence unit global" information, and it would have been a _completely_ appropriate place to put all the things that can currently be specified in `<persistence-unit-defaults>`. But I did not get a single piece of positive feedback on that proposal from a single person, and so I abandoned it. Anyway, a unit-global level annotation like that would be the correct way to solve this problem. Currently we have no such annotation.

**Comment by dmatej** [comment]
> OK, then, so I must be missing something.
> 
> So let's say I have the following legacy schema:
> 
> CREATE TABLE BOOK (ISBN VARCHAR(13) PRIMARY KEY, TITLE VARCHAR(500), TEXT CLOB);
> And this Java class:
> 
> @Entity
> class Book {
>     @Id String isbn;
>     String title;
>     String text;
> }
> and you turn on global identifier quoting.
> 
> You're telling me that this code works in EclipseLink?
> 
> How?? What SQL does EclipseLink generate?

This is wrong example, because here you don't need it at all as you DDL is strictly uppercased. Same happens when you would use lowercase.
Updating your example, what Hibernate does, if the DDL would be written this way? How should the entity look like?
```
CREATE TABLE "Book" ("ISBN" VARCHAR(13) PRIMARY KEY, "Title" VARCHAR(500), "Text" TEXT);
```
Btw by naming the column TEXT you hit a keyword in PostgreSQL. `CLOB` is not supported.

**Comment by dmatej** [comment]
> By the way, a couple of months ago, I proposed introducing a `@PersistenceModule` annotation for this sort of "persistence unit global" information, and it would have been a _completely_ appropriate place to put all the things that can currently be specified in `<persistence-unit-defaults>`. But I did not get a single piece of positive feedback on that proposal from a single person, and so I abandoned it. Anyway, a unit-global level annotation like that would be the correct way to solve this problem. Currently we have no such annotation.

Sorry, I know you work a lot on Persistence, and I would like to keep your tempo, however I have to do work also on other parts of the [EE4J ecosystem](https://projects.eclipse.org/projects/ee4j/who). I am reading emails by random. I will try to join the next meeting, unfortunately as I am bit overloaded I am forgetting meetings.

You wrote that such databases are rather rare, I don't think it is true - in my experience it was around 20% I worked with, which might be a good reason to make it easier. One other reason to have such strict option is also that in really rare cases there might be conflicts in names. Sure, you have to use `Column` and `Table` annotations.

Aha, I see, you mean this PR: https://github.com/jakartaee/persistence/pull/861 Yes, that would make sense.

**Comment by gavinking** [comment]
Part 1
-----

> This is wrong example, because here you don't need it at all as you DDL is strictly uppercased

Wrong. SQL is case insensitive, and so if I have this entity:

```java
@Entity
class Book {
    @Id String isbn;
    String title;
    String text;
}
```

Then it works perfectly with any of the following DDL:

```sql
CREATE TABLE BOOK (ISBN VARCHAR(13) PRIMARY KEY, TITLE VARCHAR(500), BODYTEXT CLOB);
```
```sql
CREATE TABLE book (isbn VARCHAR(13) PRIMARY KEY, title VARCHAR(500), bodytext CLOB);
```
```sql
CREATE TABLE Book (isbn VARCHAR(13) PRIMARY KEY, title VARCHAR(500), bodyText CLOB);
```
```sql
CREATE TABLE BoOk (isbn VARCHAR(13) PRIMARY KEY, tItLe VARCHAR(500), bOdyTeXt CLOB);
```

More importantly, this is the normal behavior of ANSI SQL, and so this is completely portable.

Part 2
-----

> what Hibernate does, if the DDL would be written this way? 

```sql
CREATE TABLE "Book" ("ISBN" VARCHAR(13) PRIMARY KEY, "Title" VARCHAR(500), "Text" TEXT);
```

Almost nobody writes DDL like this, but let's go with this example because it *perfectly* illustrates my point.

Let's say you have this DDL, and you have my entity above. **And you turn on global identifier quoting.** Then Hibernate issues SQL like this:

```sql
select "isbn", "title", "text" from "Book"
```

and this query immediately fails. Global identifier quoting _did not help_, not even in your own cherry-picked example!

> How should the entity look like?

The way to make this work portably without using some more advanced machinery in Hibernate (naming strategies), is the following:

```java
@Entity 
@Table("`Book`")
class Book {
    @Id @Column("`ISBN`")
    String isbn;
    @Column("`Title`")
    String title;
    @Column("`Text`")
    String text;
}
```

which is terrible.

So in practice anybody with a schema like this would use a `PhysicalNamingStrategy` to deal with this; global identifier quoting doesn't help much.

**Comment by dmatej** [comment]
Again, Part 1 is not relevant at all. We agreed that we work with existing db schema which is written this way and we have to reflect that. 

Btw in the past I had a tool which needed it just for the table and was able to find column names from db metadata and match them to fields. That is a bit of a sci-fi for implementations probably, but it could be doable. (EDIT: Didn't Eclipse IDE tool do it too? Or some maven plugin? I have to check ...)

The "`" character is not used by all databases if I remember well and it looks rather as a hack. Delimiter is not a part of the name, you will not receive it from JDBC metadata, for example.

**Comment by gavinking** [comment]
>  Part 1 is not relevant at all.

It's relevant because it shows why using unquoted identifiers just works better and more naturally. Claims were made here that using quoted identifiers everywhere (rather than simply avoiding collisions with reserved words) is a *better* and *recommendable* approach. And it's not; it's on balance worse and so it's not something we recommend. 

It's really quite straightforward to add an explicit `@Column` annotation in the very rare cases where you have a collision with a SQL keyword. Much easier than dealing with all the problems that use of quoted identifiers introduces. (Having to use quotes in your native SQL queries, for one.)

> The "`" character is not used by all databases if I remember well and it looks rather as a hack.

Hibernate automatically translates the backticks to whatever is the native quote character of the database: to `"`, backtick, or `[]` depending on the platform. 

If you want to do the exact same thing in a way blessed by the JPA spec, you must use `\"` instead of backtick, and it's similarly translated to the correct character, as required by the spec. 

```java
@Entity 
@Table("\"Book\"")
class Book {
    @Id @Column("\"ISBN\"")
    String isbn;
    @Column("\"Title\"")
    String title;
    @Column("\"Text\"")
    String text;
}
```

Of course the standard quote character in ANSI SQL is the double quote, so the spec is consistent with that.

> Delimiter is not a part of the name, you will not receive it from JDBC metadata, for example.

No idea what you mean by this.

**Comment by gavinking** [comment]
The bottom line is: global quoting doesn't solve the problem you're trying to solve, and introduces worse problems.

**Comment by dmatej** [comment]
> The bottom line is: global quoting doesn't solve the problem you're trying to solve, and introduces worse problems.

For example? You wrote this several times without any real example. Instead I have real world example where it worked better, and at least two real world production systems from the past 15 years which had to do that.
All you provided was an example where were no rules in the DDL. Sure, there it would not be easy, but ... it depends.

>> Delimiter is not a part of the name, you will not receive it from JDBC metadata, for example.
> No idea what you mean by this.

Quick example from https://www.baeldung.com/jdbc-database-metadata :
```java
try(ResultSet columns = databaseMetaData.getColumns(null,null, "Book", null)){
  while(columns.next()) {
    String columnName = columns.getString("COLUMN_NAME");
    String columnSize = columns.getString("COLUMN_SIZE");
    String datatype = columns.getString("DATA_TYPE");
    String isNullable = columns.getString("IS_NULLABLE");
    String isAutoIncrement = columns.getString("IS_AUTOINCREMENT");
  }
}
```
The annotation attribute is `Column.name`. Delimiters are not a part of the name - it is just a hack to make the technology work with SQL database. If there would be an attribute `useDelimiter=true` that would be ok, but you recommend we should continue with hacks.

**Comment by gavinking** [comment]
>  Instead I have real world example where it worked better

No you don't. In the example you gave, global quoting *did not work well*, as I already showed quite clearly.

> Quick example from https://www.baeldung.com/jdbc-database-metadata

Ah, OK, cool, thanks for the nice educational link to a slop website so that I can learn how to use the JDBC metadata API I guess?

Look, it's clear that you're not engaging with my quite carefully formulated arguments and code examples, and since this is getting silly now, I'm just going to re-close the issue. I don't have time for further going around in circles. Sorry. I'm just too busy these days.

If at some point we introduce something similar in concept to `@PersistenceModule`, then `delimitedIdentifiers` will naturally come along for the ride. But until that happens, we're stuck with doing it in XML.
