### ISSUE TITLE
Add possibility to add hooks to an EntityManager

### ISSUE THREAD

**Issue by patric-r** [jakartaee/persistence#328]
It would be nice to add 'hooks' to JPA in order to react on certain JPA events.
E.g., for EclipseLink there's a [SessionEventListener](https://www.eclipse.org/eclipselink/api/2.7/org/eclipse/persistence/sessions/SessionEventListener.html#preCalculateUnitOfWorkChangeSet-org.eclipse.persistence.sessions.SessionEvent-) interface.

It defines interesseting events/methods like `preCalculateUnitOfWorkChangeSet(SessionEvent)`, e.g. to have the possibility to get all list of JPA changes of an EntityManger before they even get persisted (and with the chance of altering the changes!)

I would love to see this feature in standard JPA instead of dealing with incompatible provider-specific approaches.

**Comment by gavinking** [comment]
>  I would love to see this feature in standard JPA instead of dealing with incompatible provider-specific approaches.

The reason we have incompatible provider-specific APIs is that providers work differently. 

FTR, the thing in Hibernate that looks superficially _most_ similar to the linked EclipseLink interface is our [SessionEventListener](https://docs.jboss.org/hibernate/orm/6.2/javadocs/org/hibernate/SessionEventListener.html), but apart from the name, it's not really _that_ similar. Indeed, perhaps the most analogous thing we have is our [session event](https://docs.jboss.org/hibernate/orm/6.2/javadocs/org/hibernate/event/spi/package-summary.html) framework.

Now, surely there are some operations in common. I suppose [`dirtyCalculationStart()`](https://docs.jboss.org/hibernate/orm/6.2/javadocs/org/hibernate/SessionEventListener.html#dirtyCalculationStart()) is probably quite similar to the `preCalculateUnitOfWorkChangeSet()` method you mention, but there's room for devils to hide in details, and it would take some work to nail down the semantics.

Why am I saying all this?

Well, because the issue description states neither a concrete problem affecting users of JPA, nor makes a concrete proposal: "add 'hooks' to JPA" just isn't a proper issue description.

@patric-r If this is something you would like to see in the JPA spec, then you need to specify:

- *which* "hooks" you would like to see standardized, and
- *why* you need them.

It's not enough to say that "oh every provider has some kind of hooks so let's just standardize them".

**Comment by gavinking** [comment]
Closing this issue since it lacks specificity. 

Of course anyone is welcome to open an issue which proposes actual specific new callbacks. (Along with motivation for adding them.)
