### ISSUE TITLE
Support for more Java types

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#35]
JPA currently only supports few Java types to be persisted, mostly generic types, Strings and Date. Since many applications would benefit from it, support for direct persistence of java.net.URL (as VARCHAR) and java.awt.Image (as BLOB) should be added. Both are commonly used in many applications and currently produce an overhead of manually written code when to be used in JPA entities.

In addition (or as a replacement for the above), it would be great to have the possibility to map any not supported Java type to any kind of supported Java type, in analogy to the XmlAdapters used in JAXB marshall / unmarshall. This would relax the need for special support for Image and URL. As an example how this could work, please look at the following pseudo-code, which demonstrates how java.net.URL could get marshalled to a String at time of persisting it:

@Column(name = "MY_SQL_FIELD_NAME"
@JpaAdapter(UrlJpaAdapter.class)
private URL someField;
...
public class UrlJpaAdapter.class extends JpaAdapter<String, URL> {
public URL unmarshal(String v) throws MalformedURLException

{ return new URL(v); }

public String marshal(URL v)

{ return v.toString(); }

}

**Comment by gavinking** [comment]
The functionality described here has been available in JPA for quite a long time as the `AttributeConverter` interface. (Since JPA 2.0, I believe.)

So I'm going to close this issue.

P.S. I'm sympathetic to adding `java.net.URL` as a built-in basic type, but if we need that we should create a new issue to capture that specific change.
