### ISSUE TITLE
@PrePersist / @PreUpdate / @PostPersist / @PostUpdate

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#51]
New annotations "@PrePersist" / "@PreUpdate" / "@PostPersists" / "@PostUpdate" annotations are used to define the event when the above annotations are to be injected.

@PrePersist will be the most typical use case.

Example:

@PrePersist @CurrentUser String createdBy; // Injects who created this record.
@PrePersist @CurrentTimestamp Date createdOn; // Injects when this record was created.
@PreUpdate @CurrentUser String lastUpdatedBy; // Injects who last updated this record.
@PreUpdate @CurrentTimestamp Date lastUpdatedOn; // Injects when this record was last updated.

**Comment by gavinking** [comment]
To be clear, since it's not clear from the issue description, what is really being asked for here is the ability to have auto-generated non-`@Id` values at insert and update time. This is something that has also come up on #113. And it's something that our implementation supports and surely other implementations as well.

> New annotations `@PrePersist` / `@PreUpdate` / `@PostPersist` / `@PostUpdate` annotations are used to define the event when the above annotations are to be injected.

This is a kind-of nice idea, and I must note that these would not be _new_ annotations, since they have existed in JPA since 1.0. So the proposal would really be to _reuse_ them for identifying insert-time/update-time generation. That's not a crazy idea at all and I kinda like it.

However, what I don't like is how this proposal was written up, and the lack of any activity at all in two decades.

So I'm closing this issue and moving the discussion to https://github.com/jakartaee/persistence/issues/113#issuecomment-1679298010. By closing the *issue* I'm absolutely not rejecting the *idea* it proposes.
