### ISSUE TITLE
Support schema drop on restart

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#57]
javax.persistence.schema-generation.database.action=drop-and-create only drops the schema on undeploy/deploy. For rapid/agile/iterative development via IDEs, very frequently developers start and stop the app/server without necessarily triggering a deploy/undeploy cycle hence not performing a drop. In these scenarios, developers would want a schema drop to happen on app/server stop and start. Hibernate for example, supports this feature.

Such a feature could be supported via an additional property like javax.persistence.schema-generation.database.drop-on-restart=true, that is defaulted to false.

**Comment by m-reza-rahman** [comment]
This is a very old and low priority issue. I suggest just closing this now to reduce clutter.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by gavinking** [comment]
I believe that this issue report results from a misreading of the spec.

The setting:

    javax.persistence.schema-generation.database.action=drop-and-create

means "drop and then recreate the schema from `createEntityManagerFactory()` or from `generateSchema()`", so it should certainly happen on an app server restart. This is not really clearly defined by the spec, but it can be inferred from sections 9.1 and 9.2.1.

Anyway, since the original reporter of this issue (Reza) has suggested that it be closed, I'm going to go ahead and close it
