### ISSUE TITLE
Require lazy registration of entity listeners after createContainerEntityManagerFactory() call

### ISSUE THREAD

**Issue by lukasj** [jakartaee/persistence#83]
[https://java.net/projects/jpa-spec/lists/jsr338-experts/archive/2014-01/message/3](https://java.net/projects/jpa-spec/lists/jsr338-experts/archive/2014-01/message/3) didn't get much feedback but [https://issues.jboss.org/browse/WFLY-2387](https://issues.jboss.org/browse/WFLY-2387) has gotten interest. The issue is that CDI injection allows you to inject the persistence context, and listeners support CDI injection, which may need the same persistence unit (causing a cycle). One way to resolve the cycle, is to ensure that persistence units always are available before the entity listeners are registered.

Add a requirement that entity listeners are registered after the EntityManagerFactory is created (after createContainerEntityManagerFactory(PersistenceUnitInfo, Map) returns) and before it is needed by the application.

**Comment by gavinking** [comment]
@scottmarlow is this issue still live?

**Comment by scottmarlow** [comment]
@gavinking 

I think we can close it due to a lack of feedback.  

If we decide to reopen in the future, the suggestion is to update https://jakarta.ee/specifications/persistence/3.1/jakarta-persistence-spec-3.1#entity-listeners from:

> The persistence provider is responsible for using the CDI SPI to create instances of the entity listener class; to perform injection upon such instances; to invoke their PostConstruct and PreDestroy methods, if any; and to dispose of the entity listener instances.

To something like:

> The persistence provider is responsible for using the CDI SPI to create instances of the entity listener class (after [javax.enterprise.inject.spi.AfterDeploymentValidation](https://jakarta.ee/specifications/cdi/4.0/apidocs/jakarta.cdi/jakarta/enterprise/inject/spi/afterdeploymentvalidation) event is triggered); to perform injection upon such instances; to invoke their PostConstruct and PreDestroy methods, if any; and to dispose of the entity listener instances.

**Comment by gavinking** [comment]
@scottmarlow So I went and had a look at that thread on the WildFly issue. And I'm not sure I agree with some of the conclusions reached there.

To begin with, Stuart says that we're supposed to support injection of the `EntityManager` into an entity listener. But as far as I can tell, this is explicitly _not_ required, since entity listeners are not supposed to call the `EntityManager`!

Section 3.5.2 says:

> In general, the lifecycle method of a portable application should not invoke `EntityManager` or query operations, access other entity instances, or modify relationships within the same persistence context

Now, OK, I guess listeners _can_ inject the `EntityManagerFactory`, and perhaps that's what Stuart meant.

But even then, it's not obvious to me that your proposed restriction is necessary. Is that _really_ the only possible way to implement these requirements? It seems to me that an alternative implementation would involve injecting proxies for the persistence units and validating those proxies later. I'm not saying that's the _best_ implementation, I'm just saying I don't see why we should _prohibit it_. It's the job of the spec to say what is possible, not how it is implemented.

Am I missing something here?

**Comment by gavinking** [comment]
OK, great, so then I think it's fine to close this one, right?
